In [1]:
# Dependencies and Setup

import requests
import pandas as pd
import numpy as np
import us
import matplotlib.pyplot as plt

bully_data_file = "Output/bully11.csv"
ed_data_file = "Output/ed11.csv"

In [4]:
#           ** DO NOT RUN **
#Bullying & Harassment Allegations API Pull 

base_url = "https://educationdata.urban.org"
year = "2011"

bully_dict = {}
bully_list = []

for i in range(95):
    page_num = i + 1
    bully_url = base_url + f"/api/v1/schools/crdc/harassment-or-bullying/{year}/allegations/?page={page_num}"

    response = requests.get(bully_url).json()
    results_list = response["results"]

    for j in range(len(results_list)):

        state_fips = str(response["results"][j]["fips"])
        state_name = us.states.lookup(state_fips)
        
        if (state_name == None) : 
            state_fips = "0" + str(response["results"][j]["fips"])
            state_name = us.states.lookup(state_fips)
        
        sex = str(response["results"][j]["allegations_harass_sex"])
        race = str(response["results"][j]["allegations_harass_race"])
        disability = str(response["results"][j]["allegations_harass_disability"])
        orientation = str(response["results"][j]["allegations_harass_orientation"])
        religion = str(response["results"][j]["allegations_harass_religion"])
        
        if (sex != -1 and race != -1 and disability != -1 and orientation != -1 and religion != -1):
            if (sex != -2 and race != -2 and disability != -2 and orientation != -2 and religion != -2):
                bully_dict = {"State": state_name, "Alleged_Sexual_Harassment": sex, "Alleged_Racial_Harassment": race, 
                             "Alleged_Disability_Harassment": disability, "Alleged_Orientation_Harassment": orientation, 
                              "Alleged_Religion_Harassment": religion}
                bully_list.append(bully_dict)

    print(f"Processing page {page_num} of 94")
    
    
bully_df = pd.DataFrame(bully_list)
bully_df

Processing page 1 of 94
Processing page 2 of 94
Processing page 3 of 94
Processing page 4 of 94
Processing page 5 of 94
Processing page 6 of 94
Processing page 7 of 94
Processing page 8 of 94
Processing page 9 of 94
Processing page 10 of 94
Processing page 11 of 94
Processing page 12 of 94
Processing page 13 of 94
Processing page 14 of 94
Processing page 15 of 94
Processing page 16 of 94
Processing page 17 of 94
Processing page 18 of 94
Processing page 19 of 94
Processing page 20 of 94
Processing page 21 of 94
Processing page 22 of 94
Processing page 23 of 94
Processing page 24 of 94
Processing page 25 of 94
Processing page 26 of 94
Processing page 27 of 94
Processing page 28 of 94
Processing page 29 of 94
Processing page 30 of 94
Processing page 31 of 94
Processing page 32 of 94
Processing page 33 of 94
Processing page 34 of 94
Processing page 35 of 94
Processing page 36 of 94
Processing page 37 of 94
Processing page 38 of 94
Processing page 39 of 94
Processing page 40 of 94
Processing page 41 of 94
Processing page 42 of 94
Processing page 43 of 94
Processing page 44 of 94
Processing page 45 of 94
Processing page 46 of 94
Processing page 47 of 94
Processing page 48 of 94
Processing page 49 of 94
Processing page 50 of 94
Processing page 51 of 94
Processing page 52 of 94
Processing page 53 of 94
Processing page 54 of 94
Processing page 55 of 94
Processing page 56 of 94
Processing page 57 of 94
Processing page 58 of 94
Processing page 59 of 94
Processing page 60 of 94
Processing page 61 of 94
Processing page 62 of 94
Processing page 63 of 94
Processing page 64 of 94
Processing page 65 of 94
Processing page 66 of 94
Processing page 67 of 94
Processing page 68 of 94
Processing page 69 of 94
Processing page 70 of 94
Processing page 71 of 94
Processing page 72 of 94
Processing page 73 of 94
Processing page 74 of 94
Processing page 75 of 94
Processing page 76 of 94
Processing page 77 of 94
Processing page 78 of 94
Processing page 79 of 94
Processing page 80 of 94
Processing page 81 of 94
Processing page 82 of 94
Processing page 83 of 94
Processing page 84 of 94
Processing page 85 of 94
Processing page 86 of 94
Processing page 87 of 94
Processing page 88 of 94
Processing page 89 of 94
Processing page 90 of 94
Processing page 91 of 94
Processing page 92 of 94
Processing page 93 of 94
Processing page 94 of 94
Processing page 95 of 94

,State,Alleged_Sexual_Harassment,Alleged_Racial_Harassment,Alleged_Disability_Harassment,Alleged_Orientation_Harassment,Alleged_Religion_Harassment
0,Alabama,None,None,None,None,None
1,Alabama,None,None,None,None,None
2,Alabama,None,None,None,None,None
3,Alabama,None,None,None,None,None
4,Alabama,None,None,None,None,None
...,...,...,...,...,...,...
94104,California,None,None,None,None,None
94105,California,None,None,None,None,None
94106,California,None,None,None,None,None
94107,California,None,None,None,None,None
94108,California,None,None,None,None,None

In [7]:
bully_df.loc[bully_df["Alleged_Sexual_Harassment"]!="None"]

Empty DataFrame
Columns: [State, Alleged_Sexual_Harassment, Alleged_Racial_Harassment, Alleged_Disability_Harassment, Alleged_Orientation_Harassment, Alleged_Religion_Harassment]
Index: []

In [ ]:
# ** RUN THIS CELL! **

bully_df = pd.read_csv("Output/bully11.csv")
bully_df.head()

In [5]:
# Sum allegations to make "Total_Allegations" column

bully_df["Alleged_Sexual_Harassment"] = bully_df["Alleged_Sexual_Harassment"].astype(int)
bully_df["Alleged_Racial_Harassment"] = bully_df["Alleged_Racial_Harassment"].astype(int)
bully_df["Alleged_Disability_Harassment"] = bully_df["Alleged_Disability_Harassment"].astype(int)
bully_df["Alleged_Orientation_Harassment"] = bully_df["Alleged_Orientation_Harassment"].astype(int)
bully_df["Alleged_Religion_Harassment"] = bully_df["Alleged_Religion_Harassment"].astype(int)
bully_df["Total_Allegations"]= bully_df["Alleged_Sexual_Harassment"] + bully_df["Alleged_Racial_Harassment"] + bully_df["Alleged_Disability_Harassment"] + bully_df["Alleged_Orientation_Harassment"]+ bully_df["Alleged_Religion_Harassment"]
bully_df

ValueError: invalid literal for int() with base 10: 'None'

In [33]:
# Drop rows in allegations_by_state where "State" is Washington DC or "None"

bully_df = bully_df.loc[(bully_df["State"]!="0") & (bully_df["State"]!="District of Columbia" )]

In [34]:
# Group by State to get counts for alleged bullying/harassment cases by state

bully_df["State"] = bully_df["State"].astype(str)
grouped_bully_df = bully_df.groupby("State").sum()

allegations_by_state = pd.DataFrame(grouped_bully_df)
# allegations_by_state["Total_Allegations"].plot(kind="bar")
allegations_by_state.head()

,Alleged_Sexual_Harassment,Alleged_Racial_Harassment,Alleged_Disability_Harassment,Alleged_Orientation_Harassment,Alleged_Religion_Harassment,Total_Allegations
State,,,,,,
Alabama,1040,547,117,0,0,1704
Alaska,124,22,8,0,0,154
Arizona,1947,662,177,0,0,2786
Arkansas,611,791,168,0,0,1570
California,6367,3528,1249,0,0,11144

In [35]:
#      ** DO NOT RUN **

# Write allegations_by_state DataFrame to csv 

with open(bully_data_file, "w") as bully:
    bully.write("State,Alleged_Sexual_Harassment,Alleged_Racial_Harassment,Alleged_Disability_Harassment,Alleged_Orientation_Harassment,Alleged_Religion_Harassment\n")
    
    for index,row in bully_df.iterrows():
        state = row["State"]
        sex = row["Alleged_Sexual_Harassment"]
        race = row["Alleged_Racial_Harassment"]
        disability = row["Alleged_Disability_Harassment"]
        orientation = row["Alleged_Orientation_Harassment"]
        religion = row["Alleged_Religion_Harassment"]
        
        bully.write(f"{state},{sex},{race},{disability},{orientation},{religion}\n")

In [ ]:
#To Do: 1. Group bully_df by State (allegations_by_state_df), then merge with Census demographic data on "State" (demo_bully_df)
#       2. Repeat with 2011, 2013 and combine
#       3. Merge multi-year demo_bully_df w/Geoffrey's dropout dataframe on "Year"

In [ ]:
#      ** DO NOT RUN **

#Pull in Ed Data for all States

ed_data1 = pd.read_csv("Input/2013_performance_data1.csv")
ed_data1["State"] = ed_data1["State"].astype(str)

ed_data2 = pd.read_csv("Input/2013_performance_data2.csv", low_memory=False)
ed_data2["State"] = ed_data2["State"].astype(str)

ed_data3 = pd.read_csv("Input/2013_performance_data3.csv")
ed_data3["State"] = ed_data3["State"].astype(str)

ed_data4 = pd.read_csv("Input/2013_performance_data4.csv", low_memory=False)
ed_data4["State"] = ed_data4["State"].astype(str)

# ed_data5 = pd.read_csv("Input/2013_performance_data5.csv", low_memory=False)
# ed_data5["State"] = ed_data5["State"].astype(str)

# ed_data6 = pd.read_csv("Input/2013_performance_data6.csv", low_memory=False)
# ed_data6["State"] = ed_data6["State"].astype(str)

In [ ]:
ed_data3["State"].value_counts()

In [ ]:
#      ** DO NOT RUN **

# Create combined Ed DataFrame

frames = [ed_data1,ed_data2,ed_data3,ed_data4,ed_data5,ed_data6]

ed_data = pd.concat(frames)
ed_data.head(1)

In [ ]:
ed_data["Data Description"].value_counts()

In [ ]:
#      ** DO NOT RUN **

# Clean Ed Data

# Remove non-numeric ranges from performance assessment

ed_data = ed_data.loc[(ed_data["Value"] != "PS") & (ed_data["Value"] != ".") & (ed_data["Value"] != "S")]


# Remove all single-valued performance assessment rows (want ranges)

single_index_list = []
range_index_list = []

for index,row in ed_data.iterrows():
    try:
        float(row["Value"])
        single_index_list.append(index)
    except:
        pass

ed_data = ed_data.drop(labels = single_index_list)

In [ ]:
# Value Key: "GE" = Greater than or equal to (%)
#            "LE" = Less than or equal to (%)
#            "GT" = Greater than (%)
#            "LT" = Less than (%)
#            "PS" = Data suppressed

In [ ]:
value_list = ed_data["Value"].value_counts()
value_list.loc[value_list > 100]

In [ ]:
#      ** DO NOT RUN **

#Clean up Ed Data

ed_data = ed_data.replace({"GE95":"90-100","GE90":"90-100","GE80":"80-89","GE99":"90-100","LE20":"10-19","60-69":"60-79",
                           "20-29":"20-39","55-59":"50-59","50-54":"50-59","60-64":"60-79","40-44":"40-49","35-39":"20-39",
                           "30-34":"20-39","70-79":"60-79","25-29":"20-39","70-74":"60-79","11-19":"10-19","20-24":"20-39",
                           "75-79":"60-79","85-89":"80-89","80-84":"80-89","15-19":"10-19","LE10":"0-9","10-14":"10-19",
                           "6-9":"0-9","LE5":"0-9","<50%":"LT50","<=20%":"10-19",
                           "30-39":"20-39","<50":"LT50","<=20":"10-19","21-39%":"20-39","11-19%":"10-19",
                         "15-19%":"10-19","25-29%":"20-39","20-29%":"20-39","20-24%":"20-39","<=10%":"0-9","10-14%":"10-19",
                         ">=50%":"GE50","30-39%":"20-39","30-34%":"20-39","35-39%":"20-39"})

In [ ]:
# Write cleaned Ed Data to csv

with open(ed_data_file, "w") as ed:
    ed.write("School Year,State,Description,Value,Number of Test Takers,Academic Subject,Category,Age/Grade,Grade Level,LEP Status,English Proficiency,Language,Progress Level\n")
             
    for index,row in ed_data.iterrows():
        school_year = str(row["School Year"])
        state = str(row["State"])
        description = str(row["Data Description"])
        value = str(row["Value"])
        test_takers = float(row["Number of Valid Test Takers"])
        subject = str(row["Academic Subject"])
        category = str(row["Category"])
        age_grade = str(row["Age/Grade"])
        grade_level = str(row["Grade Level"])
        lep = str(row["LEP Status Description"])
        english = str(row["English Proficiency"])
        language = str(row["Language"])
        progress = str(row["Progress Level"])
        
        
        
        ed.write(f"{school_year},{state},{description},{value},{test_takers},{subject},{category},{age_grade},{grade_level},{lep},{english},{language},{progress}\n")

In [ ]:
ed_data = pd.read_csv("Output/ed.csv")
ed_data.head()

In [ ]:
math_df = ed_data.loc[ed_data["Description"] == "Performance on Statewide Mathematics Assessment"]
reading_df = ed_data.loc[ed_data["Description"] == "Performance on Statewide Reading/Language Arts Assessment"]
science_df = ed_data.loc[ed_data["Description"] == "Performance on Statewide Science Assessment"]
grad_df = ed_data.loc[ed_data["Description"] == "Four-Year Adjusted-Cohort Graduation Rates"]

In [ ]:
# Clean math assessment dataframe

math_df["Value"].value_counts()

In [ ]:
math_df = math_df.replace({"45-49":"40-49","65-69":"60-79","90-94":"90-100",">=50":"LT50",
                          "LE1":"0-9",">=50":"GE50","<=5":"0-9","<=10":"0-10",">=80":"80-89",
                          ">=90":"90-100","0-10":"0-9","40-49":"40-59","50-59":"40-59","21-39":"20-39"})

In [ ]:
reading_df["Value"].value_counts()

In [ ]:
reading_df = reading_df.replace({">=50":"LT50","LE1":"0-9",">=50":"GE50","<=5":"0-9","<=10":"0-10",">=80":"80-89",
                                "<=1":"0-9","0-10":"0-9","45-49":"40-59","65-69":"60-79","90-94":"90-100",
                                "21-39":"20-39"})

In [ ]:
science_df["Value"].value_counts()

In [ ]:
science_df = science_df.replace({"<=1":"LT50", "<=20":"LT50","<=5":"LT50","<=10":"LT50",">=90":"GE50",
                                ">=50":"GE50", "10-19":"LT50"})

In [ ]:
# Write math, reading, and science dataframes to csv

In [ ]:
# Read in census data to combine bullying, academic, and demographic data

census_data = pd.read_csv("Input/census_data15.csv")
census_data = census_data.drop("State",1)
census_data = census_data.rename(columns={"Name":"State"})
census_data.head()

In [ ]:
bully_demo_df = pd.merge(allegations_by_state,census_data, on="State")
bully_demo_df.head()

In [ ]:
allegations_by_state = allegations_by_state.reset_index()

In [ ]:
capital_states = []

for index,row in allegations_by_state.iterrows():
    capital_state = row["State"].upper()
    capital_states.append(capital_state)

In [ ]:
allegations_by_state["State"] = capital_states
allegations_by_state.head()

In [ ]:
bully_ed_df = pd.merge(allegations_by_state,math_df, on="State")
bully_ed_df.head()

In [ ]:
# Create combined DataFrame with all state assessment scores by state

frames = [math_df,reading_df,science_df]

tests_df = pd.concat(frames)
tests_df.head()

In [ ]:
# Find scores greater than or equal to 50%

ge50_counts = []

for state in us.states.STATES:
    upper_state = str(state).upper()
    ge50 = tests_df.loc[(tests_df["Value"]=="GE50") & (tests_df["State"]==upper_state)]
    ge50_count = ge50["Value"].count()
    ge50_counts.append(ge50_count)

In [ ]:
# Plot scores GE50 vs. Bulling Allegations

y_axis = ge50_counts
x_axis = allegations_by_state["Total_Allegations"]

plt.scatter(x_axis,y_axis)
plt.xlabel("Bullying Allegations by State (2015)")
plt.ylabel("Assessment Scores GE50%")

In [ ]:
# Find scores less than 50%

lt50_counts = []

for state in us.states.STATES:
    upper_state = str(state).upper()
    lt50 = tests_df.loc[(tests_df["Value"]=="LT50") & (tests_df["State"]==upper_state)]
    lt50_count = lt50["Value"].count()
    lt50_counts.append(lt50_count)

In [ ]:
# Plot scores LT50 vs. Bulling Allegations

y_axis = lt50_counts
x_axis = allegations_by_state["Total_Allegations"]

plt.scatter(x_axis,y_axis)
plt.xlabel("Bullying Allegations by State (2015)")
plt.ylabel("Assessment Scores LT50%")